AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Meeting Summariser - Async Agentic Flow

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Architectures:
      - arm64
    Tracing: Active
    Environment:
      Variables:
        # S3 layout + versions (Athena partitioned)
        S3_PREFIX: "summaries"
        SUMMARY_SCHEMA_VERSION: "1.2"
        ATHENA_PARTITIONED: "true"
        MODEL_VERSION: "bedrock:claude-3-sonnet-20240229"
        MODEL_ID: "anthropic.claude-3-sonnet-20240229-v1:0"
        PROMPT_VERSION: "2025-09-22-a"
        INSIGHTS_VERSION: "2025-08-30-a"
        CASE_CHECK_SCHEMA_VERSION: "1.0"
        SAVE_TRANSCRIPTS: "true"
        ZOOM_PARAM_PREFIX: "/zoom/s2s"
        # A2I — set Flow ARN when ready; leave portal URL empty if not used in UI
        A2I_FLOW_ARN_CASE: "arn:aws:sagemaker:eu-west-2:058264250790:flow-definition/case-check-flow-min"
        A2I_PORTAL_URL: ""

Resources:
  ### Shared Dependencies Layer ###
  SharedDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: shared-python-libs
      Description: Common Python packages (pydantic, boto3, etc.)
      ContentUri: layers/shared-python
      CompatibleRuntimes:
        - python3.11
    Metadata:
      BuildMethod: python3.11

  ### EventBridge Event Bus ###
  SummariserEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: call-summariser-events


  ### S3 Bucket for Summaries ###
  SummaryBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: "DeleteOldSummaries"
            Prefix: "summaries/"
            Status: Enabled
            ExpirationInDays: 90
          - Id: "DeleteOldAthenaResults" # <-- NEW
            Prefix: "athena-results/"
            Status: Enabled
            ExpirationInDays: 30

  ### DynamoDB Table for Job Status ###
  SummaryJobTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: summary-job-status
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: meetingId
          AttributeType: S
      KeySchema:
        - AttributeName: meetingId
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: expiresAt
        Enabled: true

  ### DynamoDB Table for Summary Metadata Index ###
  SummaryMetadataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: summary-metadata-index
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: meetingId
          AttributeType: S
        - AttributeName: versionTimestamp
          AttributeType: S
        - AttributeName: version
          AttributeType: S
      KeySchema:
        - AttributeName: meetingId
          KeyType: HASH
        - AttributeName: versionTimestamp
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: VersionIndex
          KeySchema:
            - AttributeName: version
              KeyType: HASH
            - AttributeName: versionTimestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: expiresAt
        Enabled: true


  ### Step Functions State Machine ###
  SummariserStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: call-summariser-workflow
      DefinitionUri: statemachine/summariser-workflow.asl.json
      DefinitionSubstitutions:
        FetchTranscriptFunctionArn: !GetAtt FetchTranscriptFunction.Arn
        NormaliseRolesFunctionArn: !GetAtt NormaliseRolesFunction.Arn
        PIIDetectRedactFunctionArn: !GetAtt PIIDetectRedactFunction.Arn
        SummariseFunctionArn: !GetAtt SummariseFunction.Arn
        ValidateRepairFunctionArn: !GetAtt ValidateRepairFunction.Arn
        CaseCheckFunctionArn: !GetAtt CaseCheckFunction.Arn
        PersistSummaryFunctionArn: !GetAtt PersistSummaryFunction.Arn
        A2IReviewFunctionArn: !GetAtt A2IReviewFunction.Arn
        UpdateStatusFunctionArn: !GetAtt UpdateStatusFunction.Arn
        EventBusName: !Ref SummariserEventBus
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref FetchTranscriptFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref NormaliseRolesFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref PIIDetectRedactFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref SummariseFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref ValidateRepairFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref CaseCheckFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref PersistSummaryFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref A2IReviewFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref UpdateStatusFunction
        - EventBridgePutEventsPolicy:
            EventBusName: !Ref SummariserEventBus

  ### Step Functions Workflow Lambda Functions ###
  FetchTranscriptFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: summariser/
      Runtime: python3.11
      Layers:
        - !Ref SharedDependenciesLayer
      Handler: fetch_transcript.app.lambda_handler
      Timeout: 120
      MemorySize: 512
      Environment:
        Variables:
          SUMMARY_BUCKET: !Ref SummaryBucket
          SUMMARY_JOB_TABLE: !Ref SummaryJobTable
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref SummaryBucket
        - Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
                - ssm:PutParameter
              Resource:
                - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/zoom/s2s/*

  NormaliseRolesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: summariser/
      Runtime: python3.11
      Layers:
        - !Ref SharedDependenciesLayer
      Handler: normalise_roles.app.lambda_handler
      Timeout: 30
      MemorySize: 256

  PIIDetectRedactFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: summariser/
      Runtime: python3.11
      Layers:
        - !Ref SharedDependenciesLayer
      Handler: pii_detect_redact.app.lambda_handler
      Timeout: 60
      MemorySize: 512
      Environment:
        Variables:
          SUMMARY_BUCKET: !Ref SummaryBucket
          SUMMARY_JOB_TABLE: !Ref SummaryJobTable
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref SummaryBucket
        - Statement:
            - Effect: Allow
              Action:
                - comprehend:DetectPiiEntities
              Resource: "*"

  SummariseFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: summariser/
      Runtime: python3.11
      Layers:
        - !Ref SharedDependenciesLayer
      Handler: summarise.app.lambda_handler
      Timeout: 120
      MemorySize: 1024
      Environment:
        Variables:
          SUMMARY_BUCKET: !Ref SummaryBucket
          SUMMARY_JOB_TABLE: !Ref SummaryJobTable
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref SummaryBucket
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource:
                - arn:aws:bedrock:eu-west-2::foundation-model/anthropic.claude-3-sonnet-20240229-v1:0

  ValidateRepairFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: summariser/
      Runtime: python3.11
      Layers:
        - !Ref SharedDependenciesLayer
      Handler: validate_repair.app.lambda_handler
      Timeout: 90
      MemorySize: 512
      Environment:
        Variables:
          SUMMARY_BUCKET: !Ref SummaryBucket
          SUMMARY_JOB_TABLE: !Ref SummaryJobTable
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref SummaryBucket
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource:
                - arn:aws:bedrock:eu-west-2::foundation-model/anthropic.claude-3-sonnet-20240229-v1:0

  CaseCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: summariser/
      Runtime: python3.11
      Layers:
        - !Ref SharedDependenciesLayer
      Handler: case_check.app.lambda_handler
      Timeout: 300  # Increased for chunked processing (5 minutes)
      MemorySize: 1024
      Environment:
        Variables:
          SUMMARY_BUCKET: !Ref SummaryBucket
          SUMMARY_JOB_TABLE: !Ref SummaryJobTable
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref SummaryBucket
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource:
                - arn:aws:bedrock:eu-west-2::foundation-model/anthropic.claude-3-sonnet-20240229-v1:0

  PersistSummaryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: summariser/
      Runtime: python3.11
      Layers:
        - !Ref SharedDependenciesLayer
      Handler: persist_summary.app.lambda_handler
      Timeout: 60
      MemorySize: 512
      Environment:
        Variables:
          SUMMARY_BUCKET: !Ref SummaryBucket
          SUMMARY_JOB_TABLE: !Ref SummaryJobTable
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref SummaryBucket

  A2IReviewFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: summariser/
      Runtime: python3.11
      Layers:
        - !Ref SharedDependenciesLayer
      Handler: a2i_review.app.lambda_handler
      Timeout: 60
      MemorySize: 256
      Environment:
        Variables:
          SUMMARY_BUCKET: !Ref SummaryBucket
          SUMMARY_JOB_TABLE: !Ref SummaryJobTable
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref SummaryBucket
        - Statement:
            - Effect: Allow
              Action:
                - sagemaker:StartHumanLoop
                - sagemaker:DescribeHumanLoop
              Resource: "*"

  UpdateStatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: summariser/
      Runtime: python3.11
      Layers:
        - !Ref SharedDependenciesLayer
      Handler: update_status.app.lambda_handler
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          SUMMARY_BUCKET: !Ref SummaryBucket
          SUMMARY_JOB_TABLE: !Ref SummaryJobTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SummaryJobTable

  ### Initiate Lambda (API Gateway Trigger) ###
  InitiateSummaryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: summariser/
      Runtime: python3.11
      Layers:
        - !Ref SharedDependenciesLayer
      Handler: initiate_summary.app.lambda_handler
      Events:
        Api:
          Type: Api
          Properties:
            Path: /summarise
            Method: post
      Environment:
        Variables:
          SUMMARY_BUCKET: !Ref SummaryBucket
          SUMMARY_JOB_TABLE: !Ref SummaryJobTable
          STATE_MACHINE_ARN: !Ref SummariserStateMachine
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref SummaryBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref SummaryJobTable
        - Statement:
            - Effect: Allow
              Action:
                - states:StartExecution
              Resource: !Ref SummariserStateMachine


  ### Get Summary URL Lambda (returns signed URL for summary) ###
  GetSummaryUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: summariser/
      Runtime: python3.11
      Layers:
        - !Ref SharedDependenciesLayer
      Handler: get_summary_url.app.lambda_handler
      Events:
        Api:
          Type: Api
          Properties:
            Path: /status
            Method: get
      Environment:
        Variables:
          SUMMARY_BUCKET: !Ref SummaryBucket
          SUMMARY_JOB_TABLE: !Ref SummaryJobTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref SummaryJobTable
        - S3ReadPolicy:
            BucketName: !Ref SummaryBucket

  ListSummariesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: summariser/
      Runtime: python3.11
      Layers:
        - !Ref SharedDependenciesLayer
      Handler: list_summaries.app.lambda_handler
      Events:
        Api:
          Type: Api
          Properties:
            Path: /summaries
            Method: get
      Environment:
        Variables:
          SUMMARY_BUCKET: !Ref SummaryBucket
          SUMMARY_JOB_TABLE: !Ref SummaryJobTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref SummaryJobTable
        - S3ReadPolicy:
            BucketName: !Ref SummaryBucket

  GetCaseUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: summariser/
      Runtime: python3.11
      Layers:
        - !Ref SharedDependenciesLayer
      Handler: get_case_url.app.lambda_handler
      Events:
        Api:
          Type: Api
          Properties:
            Path: /case
            Method: get
      Environment:
        Variables:
          SUMMARY_BUCKET: !Ref SummaryBucket
          SUMMARY_JOB_TABLE: !Ref SummaryJobTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref SummaryJobTable
        - S3ReadPolicy:
            BucketName: !Ref SummaryBucket

  ### A2I Review Poller (flip IN_REVIEW -> COMPLETED)
  ReviewPollerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: summariser/
      Runtime: python3.11
      Layers:
        - !Ref SharedDependenciesLayer
      Handler: review_poller.app.lambda_handler # you add this small file
      Timeout: 60
      MemorySize: 512
      Events:
        Every5Minutes:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
            Enabled: true
      Environment:
        Variables:
          SUMMARY_BUCKET: !Ref SummaryBucket
          SUMMARY_JOB_TABLE: !Ref SummaryJobTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SummaryJobTable
        - S3ReadPolicy:
            BucketName: !Ref SummaryBucket
        - S3CrudPolicy:
            BucketName: !Ref SummaryBucket
        - Statement:
            - Effect: Allow
              Action:
                - sagemaker:DescribeHumanLoop
              Resource: "*"

  ### Health Check Endpoint ###
  HealthCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: summariser/
      Runtime: python3.11
      Layers:
        - !Ref SharedDependenciesLayer
      Handler: health_check.app.lambda_handler
      Timeout: 30
      MemorySize: 256
      Events:
        Api:
          Type: Api
          Properties:
            Path: /health
            Method: get
      Environment:
        Variables:
          SUMMARY_BUCKET: !Ref SummaryBucket
          SUMMARY_JOB_TABLE: !Ref SummaryJobTable
          MODEL_VERSION: !Ref AWS::StackName
          SUMMARY_SCHEMA_VERSION: "1.2"
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref SummaryJobTable
        - S3ReadPolicy:
            BucketName: !Ref SummaryBucket
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource:
                - arn:aws:bedrock:eu-west-2::foundation-model/anthropic.claude-3-sonnet-20240229-v1:0

  # GradioDashboardFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     Environment:
  #       Variables:
  #         PORT: "8080"
  #         AWS_LWA_PORT: "8080"
  #         AWS_LWA_READINESS_CHECK_PORT: "8080"
  #         AWS_LWA_READINESS_CHECK_PATH: /
  #         ATHENA_REGION: !Ref AWS::Region
  #         ATHENA_WORKGROUP: primary
  #         ATHENA_S3_STAGING: !Sub "s3://${SummaryBucket}/athena-results/"
  #         ATHENA_DATABASE: call_summaries
  #         GRADIO_ROOT_PATH: /ui
  #     PackageType: Image
  #     Timeout: 30
  #     MemorySize: 1024
  #     AutoPublishAlias: live
  #     ProvisionedConcurrencyConfig:
  #       ProvisionedConcurrentExecutions: 1
  #     EphemeralStorage:
  #       Size: 1024
  #     # 👇 Use FunctionUrlConfig instead of Events:FunctionUrl
  #     FunctionUrlConfig:
  #       AuthType: NONE
  #       Cors:
  #         AllowMethods: ["GET", "POST", "HEAD"]
  #         AllowOrigins: ["*"]
  #         AllowHeaders: ["*"]
  #         MaxAge: 86400
  #     Policies:
  #       - Statement:
  #           - Effect: Allow
  #             Action:
  #               - athena:StartQueryExecution
  #               - athena:GetQueryExecution
  #               - athena:GetQueryResults
  #               - athena:ListWorkGroups
  #               - athena:GetWorkGroup
  #             Resource: "*"
  #       - Statement:
  #           - Effect: Allow
  #             Action:
  #               - glue:GetDatabase
  #               - glue:GetDatabases
  #               - glue:GetTable
  #               - glue:GetTables
  #               - glue:SearchTables
  #             Resource: "*"
  #       - Statement:
  #           - Effect: Allow
  #             Action: ["s3:ListBucket"]
  #             Resource: !GetAtt SummaryBucket.Arn
  #       - Statement:
  #           - Effect: Allow
  #             Action: ["s3:GetObject", "s3:PutObject"]
  #             Resource: !Sub "${SummaryBucket.Arn}/athena-results/*"

  #   Metadata:
  #     Dockerfile: fe/Dockerfile
  #     DockerContext: .
  #     DockerTag: gradio-fe
Outputs:
  ApiUrl:
    Description: "POST endpoint to start a new summary job"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/summarise"
  # DashboardUrl:
  #   # SAM creates an implicit AWS::Lambda::Url named <FunctionLogicalId>Url
  #   Value: !GetAtt GradioDashboardFunctionUrl.FunctionUrl
  #   Description: Public URL for the Gradio dashboard
