AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: CloudWatch monitoring and alerting for Call Summarizer

Parameters:
  StackName:
    Type: String
    Default: call-summariser
    Description: Name of the main application stack
  NotificationEmail:
    Type: String
    Description: Email address for alerts (optional)
    Default: ""
  Environment:
    Type: String
    Default: prod
    AllowedValues: [dev, staging, prod]
    Description: Environment name

Conditions:
  HasNotificationEmail: !Not [!Equals [!Ref NotificationEmail, ""]]

Resources:
  # SNS Topic for alerts
  AlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${StackName}-alerts-${Environment}"
      DisplayName: Call Summarizer Alerts

  # Email subscription (optional)
  EmailSubscription:
    Type: AWS::SNS::Subscription
    Condition: HasNotificationEmail
    Properties:
      Protocol: email
      TopicArn: !Ref AlertTopic
      Endpoint: !Ref NotificationEmail

  # CloudWatch Dashboard
  MonitoringDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub "${StackName}-monitoring-${Environment}"
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "x": 0,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/Lambda", "Invocations", "FunctionName", "${StackName}-InitiateSummaryFunction" ],
                  [ ".", "Errors", ".", "." ],
                  [ ".", "Duration", ".", "." ],
                  [ ".", "Throttles", ".", "." ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "eu-west-2",
                "title": "Initiate Summary Function Metrics",
                "period": 300
              }
            },
            {
              "type": "metric",
              "x": 12,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/Lambda", "Invocations", "FunctionName", "${StackName}-ProcessSummaryFunction" ],
                  [ ".", "Errors", ".", "." ],
                  [ ".", "Duration", ".", "." ],
                  [ ".", "Throttles", ".", "." ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "eu-west-2",
                "title": "Process Summary Function Metrics",
                "period": 300
              }
            },
            {
              "type": "metric",
              "x": 0,
              "y": 6,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/SQS", "NumberOfMessagesSent", "QueueName", "${StackName}-SummaryJobsQueue" ],
                  [ ".", "NumberOfMessagesReceived", ".", "." ],
                  [ ".", "NumberOfMessagesDeleted", ".", "." ],
                  [ ".", "ApproximateNumberOfVisibleMessages", ".", "." ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "eu-west-2",
                "title": "SQS Queue Metrics",
                "period": 300
              }
            },
            {
              "type": "metric",
              "x": 12,
              "y": 6,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "CallSummarizer/Errors", "ErrorCount", "Category", "EXTERNAL_SERVICE" ],
                  [ ".", ".", ".", "USER_INPUT" ],
                  [ ".", ".", ".", "INTERNAL_ERROR" ],
                  [ ".", ".", ".", "BUSINESS_LOGIC" ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "eu-west-2",
                "title": "Application Error Metrics",
                "period": 300
              }
            },
            {
              "type": "metric",
              "x": 0,
              "y": 12,
              "width": 24,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/DynamoDB", "ConsumedReadCapacityUnits", "TableName", "summary-job-status" ],
                  [ ".", "ConsumedWriteCapacityUnits", ".", "." ],
                  [ ".", "ThrottledRequests", ".", "." ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "eu-west-2",
                "title": "DynamoDB Metrics",
                "period": 300
              }
            }
          ]
        }

  # Lambda Function Error Rate Alarm
  InitiateSummaryErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${StackName}-InitiateSummary-HighErrorRate-${Environment}"
      AlarmDescription: "High error rate in InitiateSummaryFunction"
      MetricName: ErrorRate
      Namespace: AWS/Lambda
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 0.05  # 5% error rate
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Sub "${StackName}-InitiateSummaryFunction"
      AlarmActions:
        - !Ref AlertTopic
      TreatMissingData: notBreaching

  ProcessSummaryErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${StackName}-ProcessSummary-HighErrorRate-${Environment}"
      AlarmDescription: "High error rate in ProcessSummaryFunction"
      MetricName: ErrorRate
      Namespace: AWS/Lambda
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 0.05  # 5% error rate
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Sub "${StackName}-ProcessSummaryFunction"
      AlarmActions:
        - !Ref AlertTopic
      TreatMissingData: notBreaching

  # Lambda Function Duration Alarm
  ProcessSummaryDurationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${StackName}-ProcessSummary-HighDuration-${Environment}"
      AlarmDescription: "High duration in ProcessSummaryFunction"
      MetricName: Duration
      Namespace: AWS/Lambda
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 240000  # 4 minutes (240 seconds in milliseconds)
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Sub "${StackName}-ProcessSummaryFunction"
      AlarmActions:
        - !Ref AlertTopic
      TreatMissingData: notBreaching

  # SQS Dead Letter Queue Alarm
  DeadLetterQueueAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${StackName}-DeadLetterQueue-MessagesReceived-${Environment}"
      AlarmDescription: "Messages in Dead Letter Queue"
      MetricName: NumberOfMessagesReceived
      Namespace: AWS/SQS
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: QueueName
          Value: !Sub "${StackName}-SummaryJobsDLQ"
      AlarmActions:
        - !Ref AlertTopic
      TreatMissingData: notBreaching

  # Application Error Alarm
  ApplicationErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${StackName}-Application-HighErrors-${Environment}"
      AlarmDescription: "High application error rate"
      MetricName: ErrorCount
      Namespace: CallSummarizer/Errors
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref AlertTopic
      TreatMissingData: notBreaching

  # SQS Queue Backlog Alarm
  QueueBacklogAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${StackName}-SQS-HighBacklog-${Environment}"
      AlarmDescription: "High message backlog in SQS queue"
      MetricName: ApproximateNumberOfVisibleMessages
      Namespace: AWS/SQS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 3
      Threshold: 50
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: QueueName
          Value: !Sub "${StackName}-SummaryJobsQueue"
      AlarmActions:
        - !Ref AlertTopic
      TreatMissingData: notBreaching

  # DynamoDB Throttling Alarm
  DynamoDBThrottleAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${StackName}-DynamoDB-Throttling-${Environment}"
      AlarmDescription: "DynamoDB throttling detected"
      MetricName: ThrottledRequests
      Namespace: AWS/DynamoDB
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: TableName
          Value: summary-job-status
      AlarmActions:
        - !Ref AlertTopic
      TreatMissingData: notBreaching

  # Custom Metrics for Business Logic
  SuccessfulSummariesMetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: !Sub "/aws/lambda/${StackName}-ProcessSummaryFunction"
      FilterPattern: "[timestamp, uuid, level=\"INFO\", message=\"Summary completed successfully\"]"
      MetricTransformations:
        - MetricNamespace: "CallSummarizer/Business"
          MetricName: "SuccessfulSummaries"
          MetricValue: "1"
          DefaultValue: 0

  FailedSummariesMetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: !Sub "/aws/lambda/${StackName}-ProcessSummaryFunction"
      FilterPattern: "[timestamp, uuid, level=\"ERROR\", message=\"Summary processing failed\"]"
      MetricTransformations:
        - MetricNamespace: "CallSummarizer/Business"
          MetricName: "FailedSummaries"
          MetricValue: "1"
          DefaultValue: 0

  ValidationErrorsMetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: !Sub "/aws/lambda/${StackName}-InitiateSummaryFunction"
      FilterPattern: "[timestamp, uuid, level=\"WARNING\", message=\"Validation error*\"]"
      MetricTransformations:
        - MetricNamespace: "CallSummarizer/Validation"
          MetricName: "ValidationErrors"
          MetricValue: "1"
          DefaultValue: 0

  # Business Success Rate Alarm
  BusinessSuccessRateAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${StackName}-Business-LowSuccessRate-${Environment}"
      AlarmDescription: "Low business success rate for summaries"
      Metrics:
        - Id: m1
          ReturnData: false
          MetricStat:
            Metric:
              Namespace: CallSummarizer/Business
              MetricName: SuccessfulSummaries
            Period: 900
            Stat: Sum
        - Id: m2
          ReturnData: false
          MetricStat:
            Metric:
              Namespace: CallSummarizer/Business
              MetricName: FailedSummaries
            Period: 900
            Stat: Sum
        - Id: e1
          Expression: "m1/(m1+m2)*100"
          Label: "Success Rate (%)"
      EvaluationPeriods: 2
      DatapointsToAlarm: 2
      Threshold: 90  # 90% success rate
      ComparisonOperator: LessThanThreshold
      AlarmActions:
        - !Ref AlertTopic
      TreatMissingData: notBreaching

Outputs:
  DashboardURL:
    Description: CloudWatch Dashboard URL
    Value: !Sub "https://console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#dashboards:name=${StackName}-monitoring-${Environment}"

  AlertTopicArn:
    Description: SNS Topic ARN for alerts
    Value: !Ref AlertTopic
    Export:
      Name: !Sub "${StackName}-AlertTopic-${Environment}"

  MonitoringStackStatus:
    Description: Monitoring stack deployment status
    Value: "Deployed successfully"